### PR TITLE
Migration stage 3 migrate script module

### PR DESCRIPTION
**Pull request by suarezgpablo**
Added all files for script module

### CODE REVIEW

**Comment by suarezgpablo** [comment]
@javiertuya Right now the module works in my computer but it is failing in the server because of the database credentials. Right now the properties file that contains the credentials (modevo.properties) is located in the root of the script module, let me know if I need to locate it in the root of the project instead to make it work. Otherwise, I would need in the server side the file with the correct database credentials (the same that exists for the Gitlab repository)

**Comment by javiertuya** [comment]
@suarezgpablo You have to set up the database server in the new integration test job, there, you can create the properties file with the credentials that you used when creating the container.

**Comment by suarezgpablo** [comment]
@javiertuya All test cases from the GitLab repository have been migrated to Github and the job is successful.
There are some improvements to be made like improving the commands that are executed to setup the database. Do I approach this before merging it with master or do you think that it is ready to be reviewed?

Regarding the test cases: right now I believe that I have been only working with integration tests, unless I'm mistaken. In the case of the transform module it generates the model files and objects. In the case of the script module, first it does the same as in the transform module and then it creates and executes the script, checking the script.

**Comment by javiertuya** [comment]
@suarezgpablo Better merge now, I'm going to create issues to post migration

**Pull request merged**
